modLoader="javafml"
loaderVersion="${loader_version}"
license="${mod_license}"
issueTrackerURL="https://github.com/hamarb123/MCMacOSInputFixes/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="${mod_authors}"
description='''${mod_description}'''
logoFile="icon.png"
displayURL="https://github.com/hamarb123/MCMacOSInputFixes"

[[mixins]]
config="mixins.macos_input_fixes.json"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="${neo_version_range}"
    ordering="NONE"
    side="CLIENT"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="CLIENT"
